### PR TITLE
Set up prettier

### PR DESCRIPTION
**Pull request by moeezm**
Prettier is an npm library that formats code for us. The most important things to look into are the options in the .prettierrc file as there are some ones people may or may not agree with. The docs for the options are here: https://prettier.io/docs/en/options.html

### CODE REVIEW

**Comment by moeezm** [comment]
I added a .gitattributes that changes line endings to LF (unix) instead of CRLF (windows). I don't think we'll run into this problem cause like vscode might handle it but it's good to be safe. You'll also note that Prettier should change the line endings as well.

**Comment by michal-davis** [comment]
If I understand correctly, I disagree with some of your style choices:
- bracket spacing should be false, it's a lot neater in my opinion.
- Since MySQL should get only single-quoted strings, I think our JS should be double-quoted. Plus it matches the JSON! (Technically our MySQL queries are already in backticks not quotes, but just to be super safe)
I'm posting a comment rather than changing a file so we can discuss a little.

**Comment by moeezm** [comment]
I definitely have seen some cases where it's nicer with bracket spacing but they're already usually really ugly inline or oneliner statements so you do have a point.

What do you mean by MySQL should get only single-quoted strings?

**Comment by michal-davis** [comment]
Apparently it's only with a certain mode enabled but MySQL does not accept double-quotes. It's less important, I've realized it's not always the case.
[see here](https://dev.mysql.com/doc/refman/5.7/en/string-literals.html) and [here](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes) for more.

**Comment by moeezm** [comment]
If I understand correctly, the ANSI_QUOTES option makes it so that *double quotes* can't be used. 

The exact quote from the first link is: "If the ANSI_QUOTES SQL mode is enabled, string literals can be quoted **only within single quotation marks** because a string quoted within double quotation marks is interpreted as an identifier" (emphasis mine)

**Comment by michal-davis** [comment]
Yup, got my words backwards - JS should use double-quotes, because MySQL can (sometimes) only accept single quotes and our MySQL queries would be wrapped with quotes of some kind
"a mysql query WHERE string = 'value'" is a lot nicer than 'a mysql query WHERE string = \\'value\\'' (and we still use backticks anyhow)

**Comment by moeezm** [comment]
OK makes sense. Should it be changed for JSX as well?

**Comment by michal-davis** [comment]
I'd say so

**Comment by moeezm** [comment]
Sounds good. I'll commit the changes then

**Review by michal-davis — APPROVED** [review]

**Pull request merged**
